import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ta' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation strings
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    donate: 'Donate',
    // Hero
    heroWelcome: 'Welcome to Diya Charitable Trust (TN)',
    heroMotto: '-Humanity First-',
    heroTitle: 'Illuminating Lives Through Service',
    heroSubtitle: 'Empowering Communities, Building Hope',
    heroCta: 'Join Our Mission',
    // Mission
    missionTitle: 'Our Mission',
    missionDescription: 'At Diya Charity, we are a newly established NGO dedicated to serving society through comprehensive social welfare programs. Our mission is to illuminate lives and bring hope to underserved communities through education, healthcare, women\'s empowerment, and environmental sustainability. Like a diya (lamp) that dispels darkness, we strive to light up the path towards a better tomorrow for all.',
    // Contact
    contactTitle: 'Get in Touch',
    contactDescription: 'Join us in our mission to serve society. Whether you want to volunteer, donate, or partner with us, we would love to hear from you. Together, we can make a difference in the lives of those who need it most.',
    // Footer
    footerCopyright: '© 2035 by Diya Charity.',
    footerPoweredBy: 'Powered and secured by Wix',
    privacyPolicy: 'Privacy Policy',
    accessibilityStatement: 'Accessibility Statement',
    accessibilityStatementDesc: 'Diya Charitable Trust is committed to ensuring digital accessibility for people with disabilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards. We aim to conform to the Web Content Accessibility Guidelines (WCAG) 2.1 level AA standards. If you encounter any accessibility barriers on our website, please contact us at dctnow.ngo@gmail.com and we will work to address the issue.',
    cancellationRefundsPolicy: 'Cancellation & Refunds Policy',
    legalDisclaimerCompliance: 'Legal Disclaimer & Compliance',
    close: 'Close',
    // Privacy Policy
    privacyIntro: 'Diya Charitable Trust is committed to protecting the privacy and personal information of visitors, donors, volunteers, and beneficiaries of this website.',
    privacyInfoWeCollect: 'Information We Collect',
    privacyInfoWeCollectDesc: 'We may collect personal information such as name, email address, phone number, postal address, PAN details (for donation receipts), and payment-related information when you:\n\n• Make a donation\n• Register as a volunteer\n• Contact us through forms or email\n• Subscribe to updates or newsletters\n\nPayment information is processed through secure third-party payment gateways, and we do not store card or banking details on our servers.',
    privacyUseOfInfo: 'Use of Information',
    privacyUseOfInfoDesc: 'The information collected is used solely to:\n\n• Process donations and issue receipts\n• Communicate regarding programs, acknowledgements, and updates\n• Maintain statutory records as required by Indian law\n• Improve our services and outreach activities\n\nWe do not sell, rent, or trade personal information to any third party.',
    privacyDisclosure: 'Disclosure of Information',
    privacyDisclosureDesc: 'Personal information may be shared only:\n\n• With authorized service providers (payment gateways, auditors, IT services)\n• When required by law or government authorities\n\nAll such disclosures are made strictly on a need-to-know basis.',
    privacyDataSecurity: 'Data Security',
    privacyDataSecurityDesc: 'We take reasonable administrative and technical measures to safeguard personal data against unauthorized access, misuse, or disclosure.',
    privacyCookies: 'Cookies',
    privacyCookiesDesc: 'This website may use cookies to enhance user experience and analyze website traffic. Users may choose to disable cookies through their browser settings.',
    privacyThirdPartyLinks: 'Third-Party Links',
    privacyThirdPartyLinksDesc: 'Our website may contain links to external websites. We are not responsible for the privacy practices or content of such third-party sites.',
    privacyConsent: 'Consent',
    privacyConsentDesc: 'By using this website or submitting personal information, you consent to the collection and use of information in accordance with this Privacy Policy.',
    privacyUpdates: 'Updates to This Policy',
    privacyUpdatesDesc: 'This Privacy Policy may be updated from time to time. Any changes will be posted on this page.',
    privacyContact: 'Contact Information',
    privacyContactDesc: 'For any privacy-related concerns or requests, please contact us at:\nEmail: dctnow.ngo@gmail.com',
    // Cancellation & Refunds Policy
    cancellationPolicyDesc1: 'All donations, contributions, sponsorships, and payments made to Diya Charitable Trust are voluntary and non-refundable.',
    cancellationPolicyDesc2: 'Once a donation is processed, it cannot be cancelled, reversed, or refunded, as the funds are immediately allocated toward our charitable programs and welfare activities.',
    cancellationPolicyDesc3: 'In case of duplicate transactions, technical errors, or incorrect amounts debited, donors may write to us within 7 days of the transaction with valid proof. Genuine cases will be reviewed, and refunds—if approved - will be processed within a reasonable time.',
    cancellationPolicyDesc4: 'The Trust reserves the right to decline any refund request that does not meet the above conditions.',
    cancellationPolicyDesc5: 'By making a donation on this website, the donor agrees to this policy.\n\nFor any concerns, please contact: dctnow.ngo@gmail.com',
    // Legal Disclaimer & Compliance
    legalDisclaimerDesc1: 'Diya Charitable Trust is a charitable trust registered under the Indian Trusts Act, 1882. The Trust operates on a not-for-profit basis and is committed to social welfare activities including education, nutrition, healthcare, and community development.',
    legalDisclaimerDesc2: 'All donations received are utilized solely for the objectives of the Trust. No part of the income or property of the Trust is distributed to trustees, members, or any private individual, except as reasonable compensation for services rendered in furtherance of its charitable objectives.',
    legalDisclaimerDesc3: 'Donations are voluntary and non-refundable. Issuance of donation receipts and tax benefits, if applicable, shall be subject to prevailing laws.\nTax exemption under Section 80G of the Income Tax Act, 1961 is available. Donors are advised to consult their tax advisors for confirmation of eligibility.',
    legalDisclaimerDesc4: 'At this moment until FCRA Registration Process Completion, Trust does not accept foreign contributions unless expressly permitted under the Foreign Contribution (Regulation) Act, 2010.',
    legalDisclaimerDesc5: 'All content published on this website—including text, images, logos, and materials—is the intellectual property of Diya Charitable Trust, unless otherwise stated. Unauthorized use, reproduction, or distribution is prohibited.',
    legalDisclaimerDesc6: 'While every effort is made to ensure accuracy, the Trust shall not be held liable for any errors, omissions, or outcomes arising from the use of information on this website.',
    legalDisclaimerDesc7: 'By accessing or using this website, you agree to be bound by these terms and conditions.',
    // Mission additional
    missionQuestion1: 'Have you ever felt the sting of hunger born out of extreme poverty - Even sudden urban poverty due to misfortune so deep that you couldn\'t share your struggles with anyone because of family dignity? Have you faced the stress of losing a job, along with the emotional turmoil it brings to you and your family? Have you experienced loneliness or depression from being left behind in the race for success or from the challenges that come with age? Or the pain of missing someone, something, or the helplessness of being unable to meet the needs of your loved ones?',
    missionComfort: 'We are here to be a comforting presence - A healing hand to support you, uplift you, and help you move forward.',
    missionInvitation: 'If you, the reader, feel blessed by God, live in comfort, and feel protected, we invite you to spare your time to join us as a Volunteer (OR) contribute by Donating even a small part of your abundance. Remember, what goes around comes around in multiples!',
    missionAnonymous: 'Our every outreach would be anonymous. None outside would know except professional volunteers! Reach out to us through whatsapp on 1234567890, you may not get instant replies but for sure we will reach out to you !',
    missionActions: 'It doesn\'t matter who we are ! Let our actions speak !!',
    volunteer: 'Volunteer',
    ourCompliance: 'OUR COMPLIANCE',
    // Donation
    needSupport: 'NEED SUPPORT - DONATE',
    taxBenefit: 'Get Tax Benefit (Under 80G)',
    taxBenefitDesc: 'Donations are eligible for Section 80G exemption. Just share your PAN on our',
    taxBenefitDescAfter: 'after donating.',
    whatsapp: 'WhatsApp',
    lifeIsEcho: 'LIFE IS AN ECHO',
    echo1: 'What you send out comes back. What you sow you reap.',
    echo2: 'What you give you get. What you see in others exists in you.',
    donorInfo: 'Donor Information & Contribution',
    donorName: 'Donor Name *',
    phoneNumber: 'Phone Number *',
    emailAddress: 'Email Address *',
    selectAmount: 'Select Donation Amount (INR)',
    otherAmount: 'Other Amount',
    enterCustomAmount: 'Enter custom amount',
    donationType: 'Donation Type',
    oneTimeDonation: 'One-Time Donation',
    monthlyDonation: 'Monthly Donation',
    monthlyDonationNote: 'Your donation will be automatically deducted every month from the date of registration.',
    proceedPayment: 'Proceed to Payment',
    directPayment: 'Direct Payment Details',
    scanPay: 'Scan & Pay (UPI)',
    upiQr: 'UPI QR',
    upiPlaceholder: '[Placeholder for Trust\'s UPI QR Code Image]',
    upiId: 'UPI ID',
    copy: 'Copy',
    copied: 'Copied!',
    bankTransfer: 'Bank Transfer Details',
    accountName: 'Account Name',
    bankName: 'Bank Name',
    accountNumber: 'Account Number',
    ifscCode: 'IFSC Code',
    transactionNote: '*Please share transaction details via email/WhatsApp for 80G receipt.*',
    corporateSponsors: 'OUR CORPORATE & GOVERNMENT SPONSORS',
    underCSR: 'UNDER CSR INITIATIVES',
    corporatePartner: 'Corporate Partner',
    anticipatingCSR: 'Anticipating Your CSR Sponsorship here.',
    metricsImpact: 'METRICS & IMPACT AREAS',
    educationYouth: 'Education & Youth',
    elderlyCare: 'Elderly Care',
    womenFamilies: 'Women & Families',
    emergencyRelief: 'Emergency Relief',
    willBeShared: '---------- Will be Shared with program sponsors -------------',
    // Property Donation
    propertyDonationPara1: 'As a charitable organisation, our work is sustained solely through donations and sponsorships. To establish clusters of education and feeding centres, access to suitable space is essential.',
    propertyDonationPara2: 'If you are philanthropically inclined and your circumstances permit, we invite you to donate land or property to the Trust and create a lasting legacy. The property will be dedicated exclusively to the common good, and your contribution will be honoured for generations to come.',
    propertyDonationNote: 'Kindly note that the property must be non-ancestral and free from encumbrances.',
    propertyDonationContact: 'Please message us to initiate the legal process.',
    // Community Feedback
    communityFeedback: 'Community Feedback',
    // Process
    ourProcess: 'Our Process',
    joinUs: 'Join Us',
    // Impact Stats
    ourImpact: 'Our Impact',
    impactDescription: 'Since our inception, we have been making a meaningful difference in the lives of countless individuals and communities.',
    childrenEducated: 'Children Educated',
    childrenEducatedDesc: 'Providing quality education to underprivileged children',
    healthcareCamps: 'Healthcare Camps',
    healthcareCampsDesc: 'Organizing medical camps in rural areas',
    womenEmpowered: 'Women Empowered',
    womenEmpoweredDesc: 'Training women in vocational skills',
    villagesReached: 'Villages Reached',
    villagesReachedDesc: 'Extending our services to remote communities',
    joinMakingDifference: 'Join Us in Making a Difference',
    joinMakingDifferenceDesc: 'Every contribution, no matter how small, helps us reach more people and create lasting change in communities.',
    donateNow: 'Donate Now',
    // Annathanam
    annathanam: 'Annathanam',
    annathanamQuote: 'Annadhanam is not charity - it\'s service.',
    annathanamDesc1: 'You don\'t give food to someone; you serve food to God through them.',
    annathanamDesc2: 'In many traditions, it\'s said:',
    annathanamQuote2: 'The one who eats is God in disguise.',
    annathanamDesc3: 'You need to experience extreme hunger due to abject poverty to realise Annadhan ! Well apart from abject poverty, many hesitate to seek help due to pride and self-respect - such as displaced students, children of daily labourers, labourers themselves, orphaned nomads, or even those who earn a small income but still struggle to make ends meet.',
    annathanamDesc4: 'If our Annadhan can ease their burden and help them move up the economic ladder, then why not? We serve food beyond caste creed gender or religion to anyone who walks in without pride !',
    // Primary Activities
    primaryActivitiesTitle: 'Our Primary Activities & Impact Areas',
    buddingMinds: 'Budding Minds',
    buddingMindsDesc: 'Bridging school dropout gaps, skill training, and job placement assistance for underprivileged youth.',
    youthLeap: 'Youth Leap',
    youthLeapDesc: 'Skill training, psychological counseling, and placement support specifically designed for youth empowerment.',
    vulnerableWomenFamilies: 'Vulnerable Women & Families',
    vulnerableWomenFamiliesDesc: 'Skill training, job placement, and self-help group formation focused on economic stability for women.',
    oldAgeCare: 'Old Age Care',
    oldAgeCareDesc: 'Palliative care, counseling, and accessible healthcare services for the elderly community.',
    supportSustainability: 'Environment & Sustainability',
    supportSustainabilityDesc: 'Awareness campaigns and sustainability efforts for long-term community resilience.',
    explore: 'Explore',
    // Volunteer Form
    volunteerSignUp: 'Volunteer Sign Up Form',
    personalInformation: 'Personal Information',
    firstName: 'First Name *',
    gender: 'Gender',
    selectGender: 'Select gender',
    male: 'Male',
    female: 'Female',
    nonBinary: 'Non-Binary',
    preferNotToSay: 'Prefer Not To Say',
    enterFirstName: 'Enter your first name',
    volunteerPreferences: 'Volunteer Preferences',
    eventSetup: 'Event Setup',
    registrationDesk: 'Registration Desk',
    hospitalityGuestServices: 'Hospitality/Guest Services',
    workshopFacilitation: 'Workshop Facilitation',
    marketingPromotion: 'Marketing/Promotion',
    fundraising: 'Fundraising',
    generalSupport: 'General Support',
    teaching: 'Teaching',
    availability: 'Availability',
    morning: 'Morning (8am-12pm)',
    afternoon: 'Afternoon (12pm-5pm)',
    evening: 'Evening (5pm-9pm)',
    weekdays: 'Weekdays',
    weekends: 'Weekends',
    flexibleSchedule: 'Flexible Schedule',
    additionalComments: 'Additional Comments',
    tellUsWhy: 'Tell us why you want to volunteer',
    enterAdditionalNotes: 'Enter any additional notes, skills, or specific time constraints...',
    submitVolunteerApplication: 'Submit Volunteer Application',
    sending: 'Sending...',
    volunteerTerms: 'By submitting, you agree to our volunteer terms and conditions.',
    volunteerTermsTitle: 'It\'s Time to Count Yourself In',
    volunteerTermsSubtitle: '"Unity is strength" when there is collaboration and teamwork, marvelous things can happen. Volunteer your time where it makes the most difference:',
    volunteerTermsContent: 'Our team will identify your unique skill sets, abilities, passions, talents and interests and match you with a suitable project where you can make the most difference.',
    volunteerTermsOpportunities: 'Wide range of opportunities:',
    volunteerTermsOpportunitiesDesc: 'We have a wide range of opportunities for virtual and in person, counselling, teaching, vocational training, creative arts, sports training, career guidance, awareness campaigning, community development, village upliftment, beach clean ups, lake restoration, animal welfare, creative content development among others where your skill sets, connections and personality can create a lasting impact in your community.',
    volunteerTermsMedia: 'While Volunteering we might take photos, videos and written feedback/ experience for our use.',
    volunteerTermsBelongings: 'Please ensure that you take care of all your belongings like money, baggage and personal things during your volunteering.',
    volunteerTermsLiability: 'We will not be responsible for any kind of Lost/Theft of your money, baggage and personal things during your volunteering period.',
    volunteerTermsConfidential: 'Your activity may involve knowing certain information about us, about the subjects and task entrusted to you. Such information as acquired shall be treated as "confidential information" and you agree not to share such information with anyone unless required by law with our prior permission.',
    volunteerTermsConduct: 'As a volunteer it is important to be in such a way as to create a safe, supportive, learning environment for yourself and for others around us. Hence, we request you not to engage in any disruptive speech or behaviour.',
    volunteerTermsSubstances: 'Smoking, drinking alcohol or consuming any hallucinogenic or banned drug is strictly not allowed.',
    volunteerTermsStandards: 'You agree to conduct all volunteering activities with high standards and good taste, and will do nothing to cause detriment to our reputation or goodwill.',
    volunteerTermsDocumentation: 'You agree to provide all the details and documentation as may be required for the purpose of your registration as a volunteer.',
    volunteerTermsForceMajeure: 'In the event of a "Force Majeure Event," which includes, but is not limited to, governmental restrictions, riots, terrorist attacks, epidemics, quarantine, pandemics, natural disasters such as earthquakes, tempests, floods, lightning, or acts of God, we reserve the right to cancel the Program.',
    volunteerTermsCancellation: 'You will be informed if Your volunteering is canceled, and you must adjust your travel plans in light of that information.',
    volunteerTermsCancellationLiability: 'We will not be responsible for any loss and/or damage, of whatever nature, you may incur as a result of the cancellation of Your volunteering.',
    volunteerTermsConsent: 'You give your consent to us for the collection and use of your personal information that you have provided to us while registering in connection with volunteering. We may use your information to send details of any further volunteering opportunities that may come in future.',
    volunteerTermsFinal: 'Diya Charitable Trust will not be responsible for any damages intentional or unintentional whatsoever be the case & hence you are advised to act with maturity and take ownership for actions.',
    acceptTerms: 'I have read and agree to the Terms & Conditions',
    acceptTermsRequired: 'You must accept the terms and conditions to submit your application.',
    // Footer
    contactUs: 'Contact Us',
    generalInquiries: 'General Inquiries',
    emergency: 'Emergency',
    officeLocation: 'Office Location',
    officeHours: 'Office Hours',
    mondayFriday: 'Monday - Friday: 9:00 AM - 6:00 PM',
    saturday: 'Saturday: 10:00 AM - 4:00 PM',
    sunday: 'Sunday: Closed',
    quickLinks: 'Quick Links',
    legal: 'Legal',
    followUs: 'Follow Us',
    india: 'India',
    // Community Feedback Testimonials
    testimonial1Quote: 'Diya Charity has transformed our community by providing free education to our children. They truly light up lives!',
    testimonial1Author: 'Vijaya',
    testimonial2Quote: 'The healthcare camps organized by Diya Charity have been a blessing for our village. We are forever grateful.',
    testimonial2Author: 'Kannan',
    testimonial3Quote: 'Through their women empowerment programs, I learned skills that helped me start my own business. Thank you Diya Charity!',
    testimonial3Author: 'Kaviya',
  },
  ta: {
    // Header
    donate: 'நன்கொடை',
    // Hero
    heroWelcome: 'Diya Charitable Trust (TN) உங்களை வரவேற்கிறது',
    heroMotto: '-மனிதாபிமானம் முதலில்-',
    heroTitle: 'சேவை மூலம் வாழ்க்கையை ஒளிரச் செய்தல்',
    heroSubtitle: 'சமூகங்களை அதிகாரப்படுத்துதல், நம்பிக்கையை உருவாக்குதல்',
    heroCta: 'எங்கள் பணியில் சேரவும்',
    // Mission
    missionTitle: 'எங்கள் பணி',
    missionDescription: 'டியா சாரிட்டியில், நாங்கள் விரிவான சமூக நலநலத் திட்டங்கள் மூலம் சமூகத்திற்கு சேவை செய்வதற்காக அர்ப்பணிக்கப்பட்ட புதிதாக நிறுவப்பட்ட NGO ஆகும். கல்வி, சுகாதாரம், பெண்கள் அதிகாரமளித்தல் மற்றும் சுற்றுச்சூழல் நிலைத்தன்மை மூலம் குறைந்த வசதியுள்ள சமூகங்களுக்கு வாழ்க்கையை ஒளிரச் செய்து நம்பிக்கையைக் கொண்டு வருவதே எங்கள் பணி. இருளைப் போக்கும் தீபம் போல, அனைவருக்கும் ஒரு சிறந்த நாளைக்கான பாதையை ஒளிரச் செய்ய நாங்கள் முயற்சிக்கிறோம்.',
    // Contact
    contactTitle: 'தொடர்பு கொள்ளுங்கள்',
    contactDescription: 'சமூகத்திற்கு சேவை செய்யும் எங்கள் பணியில் எங்களுடன் சேரவும். நீங்கள் தன்னார்வலராக இருக்க விரும்பினாலும், நன்கொடை அளிக்க விரும்பினாலும் அல்லது எங்களுடன் கூட்டாளியாக இருக்க விரும்பினாலும், உங்களிடமிருந்து கேட்க விரும்புகிறோம். ஒன்றாக, அதிகம் தேவைப்படுபவர்களின் வாழ்க்கையில் ஒரு வித்தியாசத்தை ஏற்படுத்தலாம்.',
    // Footer
    footerCopyright: '© 2035 டியா சாரிட்டி மூலம்.',
    footerPoweredBy: 'Wix மூலம் இயக்கப்பட்டது மற்றும் பாதுகாக்கப்பட்டது',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    accessibilityStatement: 'அணுகல்தன்மை அறிக்கை',
    accessibilityStatementDesc: 'Diya Charitable Trust மாற்றுத்திறனாளிகள் உட்பட அனைவருக்கும் டிஜிட்டல் அணுகலை உறுதிசெய்ய அர்ப்பணிக்கப்பட்டுள்ளது. நாங்கள் தொடர்ந்து அனைவருக்கும் பயனர் அனுபவத்தை மேம்படுத்தி தொடர்புடைய அணுகல் தரங்களைப் பயன்படுத்துகிறோம். வலை உள்ளடக்க அணுகல் வழிகாட்டுதல்கள் (WCAG) 2.1 நிலை AA தரங்களுக்கு இணங்க நாங்கள் நோக்கமாகக் கொண்டுள்ளோம். எங்கள் வலைத்தளத்தில் எந்த அணுகல் தடைகளையும் நீங்கள் எதிர்கொண்டால், தயவுசெய்து dctnow.ngo@gmail.com இல் எங்களைத் தொடர்பு கொள்ளவும், நாங்கள் பிரச்சினையைத் தீர்ப்போம்.',
    cancellationRefundsPolicy: 'ரத்துசெய்தல் & பணத்திரும்பப்பெறுதல் கொள்கை',
    legalDisclaimerCompliance: 'சட்ட விலக்கு & இணக்கம்',
    close: 'மூடு',
    // Privacy Policy
    privacyIntro: 'Diya Charitable Trust இந்த வலைத்தளத்தின் பார்வையாளர்கள், நன்கொடையாளர்கள், தன்னார்வலர்கள் மற்றும் பயனாளிகளின் தனியுரிமை மற்றும் தனிப்பட்ட தகவல்களைப் பாதுகாக்க அர்ப்பணிக்கப்பட்டுள்ளது.',
    privacyInfoWeCollect: 'நாங்கள் சேகரிக்கும் தகவல்',
    privacyInfoWeCollectDesc: 'நீங்கள் நன்கொடை அளிக்கும்போது, தன்னார்வலராக பதிவு செய்யும்போது, படிவங்கள் அல்லது மின்னஞ்சல் மூலம் எங்களைத் தொடர்பு கொள்ளும்போது, அல்லது புதுப்பிப்புகள் அல்லது செய்திமடல்களுக்கு குழுசேரும் போது பெயர், மின்னஞ்சல் முகவரி, தொலைபேசி எண், அஞ்சல் முகவரி, PAN விவரங்கள் (நன்கொடை ரசீதுகளுக்கு), மற்றும் பணம் தொடர்பான தகவல்கள் போன்ற தனிப்பட்ட தகவல்களை நாங்கள் சேகரிக்கலாம்.\n\nபணம் தொடர்பான தகவல்கள் பாதுகாப்பான மூன்றாம் தரப்பு பணம் கேட்வேக்கள் மூலம் செயலாக்கப்படுகின்றன, மேலும் நாங்கள் எங்கள் சர்வர்களில் அட்டை அல்லது வங்கி விவரங்களை சேமிக்கவில்லை.',
    privacyUseOfInfo: 'தகவலின் பயன்பாடு',
    privacyUseOfInfoDesc: 'சேகரிக்கப்பட்ட தகவல் பின்வருவனவற்றிற்கு மட்டுமே பயன்படுத்தப்படுகிறது:\n\n• நன்கொடைகளை செயலாக்குதல் மற்றும் ரசீதுகளை வழங்குதல்\n• திட்டங்கள், அங்கீகாரங்கள் மற்றும் புதுப்பிப்புகள் குறித்து தொடர்பு கொள்ளுதல்\n• இந்திய சட்டத்தால் தேவைப்படும் சட்டப்பூர்வ பதிவுகளை பராமரித்தல்\n• எங்கள் சேவைகள் மற்றும் வெளியீட்டு நடவடிக்கைகளை மேம்படுத்துதல்\n\nநாங்கள் எந்த மூன்றாம் தரப்பிற்கும் தனிப்பட்ட தகவல்களை விற்கவோ, வாடகைக்கு விடவோ அல்லது வர்த்தகம் செய்யவோ மாட்டோம்.',
    privacyDisclosure: 'தகவல் வெளிப்படுத்தல்',
    privacyDisclosureDesc: 'தனிப்பட்ட தகவல்கள் பின்வரும் சந்தர்ப்பங்களில் மட்டுமே பகிரப்படும்:\n\n• அங்கீகரிக்கப்பட்ட சேவை வழங்குநர்களுடன் (பணம் கேட்வேக்கள், தணிக்கையாளர்கள், IT சேவைகள்)\n• சட்டத்தால் அல்லது அரசாங்க அதிகாரிகளால் தேவைப்படும்போது\n\nஇத்தகைய அனைத்து வெளிப்படுத்தல்களும் கண்டிப்பாக தேவைக்கேற்ப அடிப்படையில் செய்யப்படுகின்றன.',
    privacyDataSecurity: 'தரவு பாதுகாப்பு',
    privacyDataSecurityDesc: 'அங்கீகரிக்கப்படாத அணுகல், தவறான பயன்பாடு அல்லது வெளிப்படுத்தலுக்கு எதிராக தனிப்பட்ட தரவுகளை பாதுகாக்க நாங்கள் நியாயமான நிர்வாக மற்றும் தொழில்நுட்ப நடவடிக்கைகளை எடுக்கிறோம்.',
    privacyCookies: 'குக்கீகள்',
    privacyCookiesDesc: 'பயனர் அனுபவத்தை மேம்படுத்தவும் வலைத்தள போக்குவரத்தை பகுப்பாய்வு செய்யவும் இந்த வலைத்தளம் குக்கீகளைப் பயன்படுத்தலாம். பயனர்கள் தங்கள் உலாவி அமைப்புகள் மூலம் குக்கீகளை முடக்க தேர்வு செய்யலாம்.',
    privacyThirdPartyLinks: 'மூன்றாம் தரப்பு இணைப்புகள்',
    privacyThirdPartyLinksDesc: 'எங்கள் வலைத்தளத்தில் வெளிப்புற வலைத்தளங்களுக்கான இணைப்புகள் இருக்கலாம். அத்தகைய மூன்றாம் தரப்பு தளங்களின் தனியுரிமை நடைமுறைகள் அல்லது உள்ளடக்கத்திற்கு நாங்கள் பொறுப்பல்ல.',
    privacyConsent: 'சம்மதம்',
    privacyConsentDesc: 'இந்த வலைத்தளத்தைப் பயன்படுத்துவதன் மூலம் அல்லது தனிப்பட்ட தகவல்களை சமர்ப்பிப்பதன் மூலம், இந்த தனியுரிமைக் கொள்கைக்கு ஏற்ப தகவல்களின் சேகரிப்பு மற்றும் பயன்பாட்டிற்கு நீங்கள் சம்மதிக்கிறீர்கள்.',
    privacyUpdates: 'இந்த கொள்கையின் புதுப்பிப்புகள்',
    privacyUpdatesDesc: 'இந்த தனியுரிமைக் கொள்கை அவ்வப்போது புதுப்பிக்கப்படலாம். எந்தவிதமான மாற்றங்களும் இந்த பக்கத்தில் வெளியிடப்படும்.',
    privacyContact: 'தொடர்பு தகவல்',
    privacyContactDesc: 'தனியுரிமை தொடர்பான எந்த கவலைகள் அல்லது கோரிக்கைகளுக்கும், தயவுசெய்து எங்களைத் தொடர்பு கொள்ளவும்:\nமின்னஞ்சல்: dctnow.ngo@gmail.com',
    // Cancellation & Refunds Policy
    cancellationPolicyDesc1: 'Diya Charitable Trust-க்கு செய்யப்படும் அனைத்து நன்கொடைகள், பங்களிப்புகள், நிதியளிப்புகள் மற்றும் கொடுப்பனவுகள் தன்னார்வமானவை மற்றும் பணத்திரும்பப்பெற முடியாதவை.',
    cancellationPolicyDesc2: 'நன்கொடை செயலாக்கப்பட்டவுடன், அது ரத்து செய்யப்படவோ, மாற்றப்படவோ அல்லது பணத்திரும்பப்பெறப்படவோ முடியாது, ஏனெனில் நிதிகள் உடனடியாக எங்கள் அறப்பணி திட்டங்கள் மற்றும் நலன்புரி நடவடிக்கைகளுக்கு ஒதுக்கப்படுகின்றன.',
    cancellationPolicyDesc3: 'நகல் பரிவர்த்தனைகள், தொழில்நுட்ப பிழைகள் அல்லது தவறான தொகைகள் வசூலிக்கப்பட்டால், நன்கொடையாளர்கள் பரிவர்த்தனையிலிருந்து 7 நாட்களுக்குள் செல்லுபடியாகும் ஆதாரத்துடன் எங்களுக்கு எழுதலாம். உண்மையான வழக்குகள் மதிப்பாய்வு செய்யப்படும், மேலும் அனுமதிக்கப்பட்டால் பணத்திரும்பப்பெறுதல் நியாயமான நேரத்திற்குள் செயலாக்கப்படும்.',
    cancellationPolicyDesc4: 'மேலே உள்ள நிபந்தனைகளை பூர்த்தி செய்யாத எந்த பணத்திரும்பப்பெறுதல் கோரிக்கையையும் நிராகரிக்க Trust-க்கு உரிமை உள்ளது.',
    cancellationPolicyDesc5: 'இந்த வலைத்தளத்தில் நன்கொடை செய்வதன் மூலம், நன்கொடையாளர் இந்த கொள்கைக்கு ஒப்புக்கொள்கிறார்.\n\nஎந்த கவலைகளுக்கும், தயவுசெய்து தொடர்பு கொள்ளவும்: dctnow.ngo@gmail.com',
    // Legal Disclaimer & Compliance
    legalDisclaimerDesc1: 'Diya Charitable Trust என்பது இந்திய Trusts Act, 1882-ன் கீழ் பதிவு செய்யப்பட்ட ஒரு அறக்கட்டளை. Trust இலாப நோக்கற்ற அடிப்படையில் செயல்படுகிறது மற்றும் கல்வி, ஊட்டச்சத்து, சுகாதாரம் மற்றும் சமூக மேம்பாடு உட்பட சமூக நலன்புரி நடவடிக்கைகளுக்கு அர்ப்பணிக்கப்பட்டுள்ளது.',
    legalDisclaimerDesc2: 'பெறப்பட்ட அனைத்து நன்கொடைகளும் Trust-ன் நோக்கங்களுக்காக மட்டுமே பயன்படுத்தப்படுகின்றன. Trust-ன் வருமானம் அல்லது சொத்தின் எந்த பகுதியும் அறப்பணி நோக்கங்களை முன்னேற்றுவதற்காக வழங்கப்பட்ட சேவைகளுக்கு நியாயமான இழப்பீடு தவிர, Trustees, உறுப்பினர்கள் அல்லது எந்த தனிப்பட்ட நபருக்கும் விநியோகிக்கப்படாது.',
    legalDisclaimerDesc3: 'நன்கொடைகள் தன்னார்வமானவை மற்றும் பணத்திரும்பப்பெற முடியாதவை. நன்கொடை ரசீதுகள் மற்றும் வரி நன்மைகள், பொருந்துமானால், நடைமுறையில் உள்ள சட்டங்களுக்கு உட்பட்டது.\nIncome Tax Act, 1961-ன் Section 80G-ன் கீழ் வரி விலக்கு கிடைக்கிறது. தகுதியை உறுதிப்படுத்த நன்கொடையாளர்கள் தங்கள் வரி ஆலோசகர்களைக் கலந்தாலோசிக்க அறிவுறுத்தப்படுகிறார்கள்.',
    legalDisclaimerDesc4: 'தற்போது FCRA பதிவு செயல்முறை நிறைவடையும் வரை, Foreign Contribution (Regulation) Act, 2010-ன் கீழ் வெளிப்படையாக அனுமதிக்கப்படாத வரை, Trust வெளிநாட்டு பங்களிப்புகளை ஏற்காது.',
    legalDisclaimerDesc5: 'இந்த வலைத்தளத்தில் வெளியிடப்பட்ட அனைத்து உள்ளடக்கமும்—உரை, படங்கள், லோகோக்கள் மற்றும் பொருட்கள் உட்பட—வேறுவிதமாக குறிப்பிடப்படாவிட்டால், Diya Charitable Trust-ன் அறிவுசார் சொத்து. அங்கீகரிக்கப்படாத பயன்பாடு, பிரதியெடுத்தல் அல்லது விநியோகம் தடைசெய்யப்பட்டுள்ளது.',
    legalDisclaimerDesc6: 'துல்லியத்தை உறுதிப்படுத்த அனைத்து முயற்சிகளும் மேற்கொள்ளப்பட்ட போதிலும், இந்த வலைத்தளத்தில் உள்ள தகவல்களின் பயன்பாட்டிலிருந்து எழும் எந்த பிழைகள், தவறுகள் அல்லது விளைவுகளுக்கும் Trust பொறுப்பல்ல.',
    legalDisclaimerDesc7: 'இந்த வலைத்தளத்தை அணுகுவதன் மூலம் அல்லது பயன்படுத்துவதன் மூலம், நீங்கள் இந்த விதிமுறைகள் மற்றும் நிபந்தனைகளால் கட்டுப்படுத்தப்படுவதற்கு ஒப்புக்கொள்கிறீர்கள்.',
    // Mission additional
    missionQuestion1: 'தீவிர வறுமையால் ஏற்படும் பசியின் குத்தலை நீங்கள் எப்போதாவது உணர்ந்திருக்கிறீர்களா - குடும்ப கண்ணியம் காரணமாக உங்கள் போராட்டங்களை யாருடனும் பகிர்ந்து கொள்ள முடியாத அளவுக்கு துரதிர்ஷ்டம் காரணமாக திடீர் நகர்ப்புற வறுமை? வேலையை இழப்பதால் ஏற்படும் மன அழுத்தத்தையும், அது உங்களுக்கும் உங்கள் குடும்பத்திற்கும் கொண்டு வரும் உணர்ச்சி குழப்பத்தையும் நீங்கள் எதிர்கொண்டிருக்கிறீர்களா? வெற்றிக்கான பந்தயத்தில் பின்தங்கியதால் அல்லது வயதுடன் வரும் சவால்களால் ஏற்படும் தனிமை அல்லது மனச்சோர்வை நீங்கள் அனுபவித்திருக்கிறீர்களா? அல்லது யாரையோ, எதையோ இழப்பதால் ஏற்படும் வலி அல்லது உங்கள் அன்புக்குரியவர்களின் தேவைகளை பூர்த்தி செய்ய முடியாததால் ஏற்படும் உதவியற்ற நிலை?',
    missionComfort: 'நாங்கள் இங்கே ஒரு ஆறுதல் அளிக்கும் இருப்பு - உங்களை ஆதரிக்க, உங்களை உயர்த்த, மற்றும் முன்னேற உதவும் ஒரு குணப்படுத்தும் கை.',
    missionInvitation: 'நீங்கள், வாசகர், கடவுளால் ஆசீர்வதிக்கப்பட்டவர் என்று உணர்ந்தால், வசதியாக வாழ்கிறீர்கள், மற்றும் பாதுகாக்கப்பட்டவர் என்று உணர்ந்தால், தன்னார்வலராக எங்களுடன் சேர நேரத்தை ஒதுக்குமாறு அல்லது உங்கள் செழுமையின் ஒரு சிறிய பகுதியையும் நன்கொடையாக பங்களிக்குமாறு அழைக்கிறோம். நினைவில் கொள்ளுங்கள், சுற்றி வருவது பெருக்கங்களில் வரும்!',
    missionAnonymous: 'எங்கள் ஒவ்வொரு வெளியீடும் அநாமதேயமாக இருக்கும். தொழில்முறை தன்னார்வலர்களைத் தவிர வேறு யாருக்கும் தெரியாது! 1234567890 என்ற whatsapp மூலம் எங்களைத் தொடர்பு கொள்ளுங்கள், நீங்கள் உடனடி பதில்களைப் பெறாமல் போகலாம் ஆனால் நிச்சயமாக நாங்கள் உங்களைத் தொடர்பு கொள்வோம்!',
    missionActions: 'நாங்கள் யார் என்பது முக்கியமல்ல! எங்கள் செயல்கள் பேசட்டும் !!',
    volunteer: 'தன்னார்வலர்',
    ourCompliance: 'எங்கள் இணக்கம்',
    // Donation
    needSupport: 'ஆதரவு தேவை - நன்கொடை',
    taxBenefit: 'வரி நன்மை பெறுங்கள் (80G கீழ்)',
    taxBenefitDesc: 'நன்கொடைகள் பிரிவு 80G விலக்குக்கு தகுதியானவை. நன்கொடை அளித்த பிறகு எங்கள்',
    taxBenefitDescAfter: 'இல் உங்கள் PAN ஐ பகிர்ந்து கொள்ளுங்கள்.',
    whatsapp: 'WhatsApp',
    lifeIsEcho: 'வாழ்க்கை ஒரு எதிரொலி',
    echo1: 'நீங்கள் அனுப்புவது திரும்ப வரும். நீங்கள் விதைப்பது நீங்கள் அறுவடை செய்வீர்கள்.',
    echo2: 'நீங்கள் கொடுப்பது நீங்கள் பெறுவீர்கள். மற்றவர்களில் நீங்கள் பார்க்கும் விஷயம் உங்களில் உள்ளது.',
    donorInfo: 'நன்கொடையாளர் தகவல் மற்றும் பங்களிப்பு',
    donorName: 'நன்கொடையாளர் பெயர் *',
    phoneNumber: 'தொலைபேசி எண் *',
    emailAddress: 'மின்னஞ்சல் முகவரி *',
    selectAmount: 'நன்கொடை தொகையைத் தேர்ந்தெடுக்கவும் (INR)',
    otherAmount: 'மற்ற தொகை',
    enterCustomAmount: 'தனிப்பயன் தொகையை உள்ளிடவும்',
    donationType: 'நன்கொடை வகை',
    oneTimeDonation: 'ஒரு முறை நன்கொடை',
    monthlyDonation: 'மாதாந்திர நன்கொடை',
    monthlyDonationNote: 'பதிவு தேதியிலிருந்து ஒவ்வொரு மாதமும் உங்கள் நன்கொடை தானாக கழிக்கப்படும்.',
    proceedPayment: 'கட்டணத்திற்கு தொடரவும்',
    directPayment: 'நேரடி கட்டண விவரங்கள்',
    scanPay: 'ஸ்கேன் & பே (UPI)',
    upiQr: 'UPI QR',
    upiPlaceholder: '[Trust இன் UPI QR குறியீட்டு படத்திற்கான பிளேஸ்ஹோல்டர்]',
    upiId: 'UPI ID',
    copy: 'நகலெடு',
    copied: 'நகலெடுக்கப்பட்டது!',
    bankTransfer: 'வங்கி பரிமாற்ற விவரங்கள்',
    accountName: 'கணக்கு பெயர்',
    bankName: 'வங்கி பெயர்',
    accountNumber: 'கணக்கு எண்',
    ifscCode: 'IFSC குறியீடு',
    transactionNote: '*80G ரசீதுக்கு மின்னஞ்சல்/WhatsApp மூலம் பரிவர்த்தனை விவரங்களைப் பகிர்ந்து கொள்ளவும்.*',
    corporateSponsors: 'எங்கள் கார்ப்பரேட் & அரசாங்க நிதியளிப்பாளர்கள்',
    underCSR: 'CSR முன்முயற்சிகளின் கீழ்',
    corporatePartner: 'கார்ப்பரேட் பங்காளி',
    anticipatingCSR: 'உங்கள் CSR நிதியளிப்பை இங்கே எதிர்பார்த்துக்கொண்டிருக்கிறோம்.',
    metricsImpact: 'மெட்ரிக்ஸ் & தாக்க பகுதிகள்',
    educationYouth: 'கல்வி & இளைஞர்கள்',
    elderlyCare: 'முதியோர் பராமரிப்பு',
    womenFamilies: 'பெண்கள் & குடும்பங்கள்',
    emergencyRelief: 'அவசர நிவாரணம்',
    willBeShared: '---------- திட்ட நிதியளிப்பாளர்களுடன் பகிரப்படும் -------------',
    // Property Donation
    propertyDonationPara1: 'ஒரு அறக்கட்டளை அமைப்பாக, எங்கள் பணி முழுமையாக நன்கொடைகள் மற்றும் நிதியளிப்புகள் மூலம் நடைபெறுகிறது. கல்வி மற்றும் உணவு மையங்களின் குழுக்களை நிறுவ, பொருத்தமான இடத்திற்கான அணுகல் அவசியம்.',
    propertyDonationPara2: 'நீங்கள் தாராள மனப்பான்மை கொண்டவராகவும், உங்கள் சூழ்நிலைகள் அனுமதிக்குமானால், நாங்கள் உங்களை டிரஸ்டிற்கு நிலம் அல்லது சொத்தை நன்கொடையாக வழங்கி நீடித்த மரபை உருவாக்க அழைக்கிறோம். சொத்து பிரத்தியேகமாக பொதுநலனுக்காக அர்ப்பணிக்கப்படும், மற்றும் உங்கள் பங்களிப்பு தலைமுறைகளுக்கு கெளரவிக்கப்படும்.',
    propertyDonationNote: 'சொத்து பாரம்பரியமற்றதாகவும், கடன்களிலிருந்து விடுபட்டதாகவும் இருக்க வேண்டும் என்பதை நினைவில் கொள்ளவும்.',
    propertyDonationContact: 'சட்ட செயல்முறையைத் தொடங்க எங்களுக்கு செய்தி அனுப்பவும்.',
    // Community Feedback
    communityFeedback: 'சமூக கருத்து',
    // Process
    ourProcess: 'எங்கள் செயல்முறை',
    joinUs: 'எங்களுடன் சேருங்கள்',
    // Impact Stats
    ourImpact: 'எங்கள் தாக்கம்',
    impactDescription: 'எங்கள் தொடக்கத்திலிருந்து, எண்ணற்ற தனிநபர்கள் மற்றும் சமூகங்களின் வாழ்க்கையில் அர்த்தமுள்ள மாற்றத்தை ஏற்படுத்தி வருகிறோம்.',
    childrenEducated: 'குழந்தைகள் கல்வி',
    childrenEducatedDesc: 'வசதியற்ற குழந்தைகளுக்கு தரமான கல்வி வழங்குதல்',
    healthcareCamps: 'சுகாதார முகாம்கள்',
    healthcareCampsDesc: 'கிராமப்புற பகுதிகளில் மருத்துவ முகாம்கள் ஏற்பாடு செய்தல்',
    womenEmpowered: 'பெண்கள் அதிகாரமளிக்கப்பட்டனர்',
    womenEmpoweredDesc: 'பெண்களுக்கு தொழில்முறை திறன்கள் பயிற்சி',
    villagesReached: 'கிராமங்கள் அடைந்தன',
    villagesReachedDesc: 'தொலைதூர சமூகங்களுக்கு எங்கள் சேவைகளை விரிவாக்குதல்',
    joinMakingDifference: 'வித்தியாசத்தை ஏற்படுத்த எங்களுடன் சேருங்கள்',
    joinMakingDifferenceDesc: 'ஒவ்வொரு பங்களிப்பும், எவ்வளவு சிறியதாக இருந்தாலும், அதிகமான மக்களை அடையவும் சமூகங்களில் நீடித்த மாற்றத்தை உருவாக்கவும் எங்களுக்கு உதவுகிறது.',
    donateNow: 'இப்போது நன்கொடை',
    // Annathanam
    annathanam: 'அன்னதானம்',
    annathanamQuote: 'அன்னதானம் அறப்பணி அல்ல - அது சேவை.',
    annathanamDesc1: 'நீங்கள் ஒருவருக்கு உணவு கொடுப்பதில்லை; நீங்கள் அவர்கள் மூலம் கடவுளுக்கு உணவு பரிமாறுகிறீர்கள்.',
    annathanamDesc2: 'பல மரபுகளில், கூறப்படுகிறது:',
    annathanamQuote2: 'உண்பவர் மாறுவேடத்தில் கடவுள்.',
    annathanamDesc3: 'அன்னதானத்தை உணர நீங்கள் தீவிர வறுமையால் ஏற்படும் தீவிர பசியை அனுபவிக்க வேண்டும்! தீவிர வறுமையைத் தவிர, பெருமை மற்றும் சுயமரியாதை காரணமாக பலர் உதவி கேட்க தயங்குகிறார்கள் - இடம்பெயர்ந்த மாணவர்கள், தினசரி தொழிலாளர்களின் குழந்தைகள், தொழிலாளர்கள் தங்களை, அனாதை நாடோடிகள், அல்லது சிறிய வருமானம் ஈட்டினாலும் இன்னும் முன்னேற போராடுபவர்கள் போன்றவர்கள்.',
    annathanamDesc4: 'எங்கள் அன்னதானம் அவர்களின் சுமையை குறைத்து பொருளாதார ஏணியில் மேலே செல்ல உதவ முடியும் என்றால், ஏன் இல்லை? நாங்கள் சாதி சமயம் பாலினம் அல்லது மதத்தைத் தாண்டி பெருமை இல்லாமல் நுழையும் எவருக்கும் உணவு பரிமாறுகிறோம்!',
    // Primary Activities
    primaryActivitiesTitle: 'எங்கள் முதன்மை செயல்பாடுகள் & தாக்க பகுதிகள்',
    buddingMinds: 'முளைக்கும் மனங்கள்',
    buddingMindsDesc: 'பள்ளி கைவிடும் இடைவெளிகளை இணைத்தல், திறன் பயிற்சி, மற்றும் வசதியற்ற இளைஞர்களுக்கு வேலை வைப்பு உதவி.',
    youthLeap: 'இளைஞர் தாவல்',
    youthLeapDesc: 'இளைஞர் அதிகாரமளிப்புக்காக குறிப்பாக வடிவமைக்கப்பட்ட திறன் பயிற்சி, உளவியல் ஆலோசனை, மற்றும் வைப்பு ஆதரவு.',
    vulnerableWomenFamilies: 'எளிதில் பாதிக்கப்படும் பெண்கள் & குடும்பங்கள்',
    vulnerableWomenFamiliesDesc: 'பெண்களுக்கான பொருளாதார நிலைத்தன்மையில் கவனம் செலுத்தும் திறன் பயிற்சி, வேலை வைப்பு, மற்றும் சுய உதவி குழு உருவாக்கம்.',
    oldAgeCare: 'முதியோர் பராமரிப்பு',
    oldAgeCareDesc: 'முதியோர் சமூகத்திற்கான பராமரிப்பு சிகிச்சை, ஆலோசனை, மற்றும் அணுகக்கூடிய சுகாதார சேவைகள்.',
    supportSustainability: 'சூழல் & நிலைத்தன்மை',
    supportSustainabilityDesc: 'நீண்ட கால சமூக நிலைத்தன்மைக்கான விழிப்புணர்வு பிரச்சாரங்கள் மற்றும் நிலைத்தன்மை முயற்சிகள்.',
    explore: 'ஆராயவும்',
    // Volunteer Form
    volunteerSignUp: 'தன்னார்வலர் பதிவு படிவம்',
    personalInformation: 'தனிப்பட்ட தகவல்',
    firstName: 'முதல் பெயர் *',
    gender: 'பாலினம்',
    selectGender: 'பாலினத்தைத் தேர்ந்தெடுக்கவும்',
    male: 'ஆண்',
    female: 'பெண்',
    nonBinary: 'இருபாலினம் அல்லாத',
    preferNotToSay: 'சொல்ல விரும்பவில்லை',
    enterFirstName: 'உங்கள் முதல் பெயரை உள்ளிடவும்',
    volunteerPreferences: 'தன்னார்வலர் விருப்பங்கள்',
    eventSetup: 'நிகழ்வு அமைப்பு',
    registrationDesk: 'பதிவு மேசை',
    hospitalityGuestServices: 'விருந்தோம்பல்/விருந்தினர் சேவைகள்',
    workshopFacilitation: 'பட்டறை வசதி',
    marketingPromotion: 'சந்தைப்படுத்தல்/விளம்பரம்',
    fundraising: 'நிதி திரட்டல்',
    generalSupport: 'பொது ஆதரவு',
    teaching: 'கற்பித்தல்',
    availability: 'கிடைக்கும் நேரம்',
    morning: 'காலை (8am-12pm)',
    afternoon: 'மதியம் (12pm-5pm)',
    evening: 'மாலை (5pm-9pm)',
    weekdays: 'வார நாட்கள்',
    weekends: 'வார இறுதி',
    flexibleSchedule: 'நெகிழ்வான அட்டவணை',
    additionalComments: 'கூடுதல் கருத்துகள்',
    tellUsWhy: 'நீங்கள் ஏன் தன்னார்வலராக இருக்க விரும்புகிறீர்கள் என்பதை எங்களிடம் சொல்லுங்கள்',
    enterAdditionalNotes: 'கூடுதல் குறிப்புகள், திறன்கள் அல்லது குறிப்பிட்ட நேர கட்டுப்பாடுகளை உள்ளிடவும்...',
    submitVolunteerApplication: 'தன்னார்வலர் விண்ணப்பத்தை சமர்ப்பிக்கவும்',
    sending: 'அனுப்புகிறது...',
    volunteerTerms: 'சமர்ப்பிப்பதன் மூலம், நீங்கள் எங்கள் தன்னார்வலர் விதிமுறைகள் மற்றும் நிபந்தனைகளுக்கு ஒப்புக்கொள்கிறீர்கள்.',
    volunteerTermsTitle: 'உங்களை எண்ணுவதற்கான நேரம்',
    volunteerTermsSubtitle: '"ஒற்றுமைதான் வலிமை" ஒத்துழைப்பு மற்றும் குழுப்பணி இருக்கும்போது, அற்புதமான விஷயங்கள் நடக்கும். அதிக மாற்றத்தை ஏற்படுத்தக்கூடிய இடத்தில் உங்கள் நேரத்தை தன்னார்வலராக வழங்குங்கள்:',
    volunteerTermsContent: 'எங்கள் குழு உங்கள் தனித்துவமான திறன் தொகுப்புகள், திறன்கள், ஆர்வங்கள், திறமைகள் மற்றும் ஆர்வங்களை அடையாளம் கண்டு, நீங்கள் அதிக மாற்றத்தை ஏற்படுத்தக்கூடிய பொருத்தமான திட்டத்துடன் பொருத்துவோம்.',
    volunteerTermsOpportunities: 'விரிவான வாய்ப்புகள்:',
    volunteerTermsOpportunitiesDesc: 'மெய்நிகர் மற்றும் நேரில், ஆலோசனை, கற்பித்தல், தொழில் பயிற்சி, படைப்பு கலைகள், விளையாட்டு பயிற்சி, தொழில் வழிகாட்டுதல், விழிப்புணர்வு பிரச்சாரம், சமூக மேம்பாடு, கிராம மேம்பாடு, கடற்கரை சுத்தம், ஏரி மீட்பு, விலங்கு நலன், படைப்பு உள்ளடக்க மேம்பாடு உட்பட பல்வேறு வாய்ப்புகள் உள்ளன, அங்கு உங்கள் திறன் தொகுப்புகள், இணைப்புகள் மற்றும் ஆளுமை உங்கள் சமூகத்தில் நீடித்த தாக்கத்தை ஏற்படுத்தும்.',
    volunteerTermsMedia: 'தன்னார்வலராக இருக்கும்போது, நாங்கள் எங்கள் பயன்பாட்டிற்காக புகைப்படங்கள், வீடியோக்கள் மற்றும் எழுதப்பட்ட கருத்து/அனுபவத்தை எடுக்கலாம்.',
    volunteerTermsBelongings: 'தயவுசெய்து உங்கள் தன்னார்வலராக இருக்கும்போது பணம், ச baggage ஜம் மற்றும் தனிப்பட்ட விஷயங்கள் போன்ற உங்கள் அனைத்து சொத்துக்களையும் நீங்கள் கவனித்துக்கொள்கிறீர்கள் என்பதை உறுதிப்படுத்தவும்.',
    volunteerTermsLiability: 'உங்கள் தன்னார்வலர் காலத்தில் உங்கள் பணம், ச baggage ஜம் மற்றும் தனிப்பட்ட விஷயங்களின் எந்தவிதமான இழப்பு/திருட்டுக்கும் நாங்கள் பொறுப்பல்ல.',
    volunteerTermsConfidential: 'உங்கள் செயல்பாடு எங்களைப் பற்றிய, உங்களுக்கு ஒப்படைக்கப்பட்ட பாடங்கள் மற்றும் பணிகளைப் பற்றிய சில தகவல்களை அறிய உள்ளடக்கியிருக்கலாம். இத்தகைய தகவல்கள் "ரகசிய தகவல்" எனக் கருதப்படும் மற்றும் சட்டத்தால் தேவைப்படாத வரை எங்கள் முன் அனுமதியுடன் யாருடனும் பகிர்ந்து கொள்ளாதீர்கள்.',
    volunteerTermsConduct: 'தன்னார்வலராக, உங்களுக்கும் எங்களைச் சுற்றியுள்ள மற்றவர்களுக்கும் பாதுகாப்பான, ஆதரவான, கற்றல் சூழலை உருவாக்கும் வகையில் இருக்க வேண்டும். எனவே, எந்தவிதமான சீர்குலைக்கும் பேச்சு அல்லது நடத்தையில் ஈடுபட வேண்டாம் என்று கேட்டுக்கொள்கிறோம்.',
    volunteerTermsSubstances: 'புகைபிடித்தல், மது அருந்துதல் அல்லது எந்தவிதமான மாயத்திரவியம் அல்லது தடைசெய்யப்பட்ட மருந்தை உட்கொள்வது கண்டிப்பாக அனுமதிக்கப்படாது.',
    volunteerTermsStandards: 'அனைத்து தன்னார்வலர் செயல்பாடுகளையும் உயர் தரங்கள் மற்றும் நல்ல சுவையுடன் நடத்துவதற்கு நீங்கள் ஒப்புக்கொள்கிறீர்கள், மேலும் எங்கள் புகழ் அல்லது நல்லெண்ணத்திற்கு தீங்கு விளைவிக்க எதுவும் செய்ய மாட்டீர்கள்.',
    volunteerTermsDocumentation: 'தன்னார்வலராக உங்கள் பதிவுக்கு தேவையான அனைத்து விவரங்கள் மற்றும் ஆவணங்களையும் வழங்குவதற்கு நீங்கள் ஒப்புக்கொள்கிறீர்கள்.',
    volunteerTermsForceMajeure: '"பல வலிமை நிகழ்வு" நிகழ்வில், இதில் அரசாங்க கட்டுப்பாடுகள், கலகங்கள், பயங்கரவாத தாக்குதல்கள், தொற்றுநோய்கள், தனிமைப்படுத்தல், தொற்றுநோய்கள், நிலநடுக்கங்கள், புயல்கள், வெள்ளம், மின்னல் போன்ற இயற்கை பேரழிவுகள் அல்லது கடவுளின் செயல்கள் ஆகியவை அடங்கும், நாங்கள் திட்டத்தை ரத்து செய்ய உரிமை கொண்டுள்ளோம்.',
    volunteerTermsCancellation: 'உங்கள் தன்னார்வலர் ரத்து செய்யப்பட்டால் உங்களுக்கு தெரிவிக்கப்படும், மேலும் அந்த தகவலைக் கருத்தில் கொண்டு நீங்கள் உங்கள் பயணத் திட்டங்களை சரிசெய்ய வேண்டும்.',
    volunteerTermsCancellationLiability: 'உங்கள் தன்னார்வலர் ரத்து செய்வதன் விளைவாக நீங்கள் எந்தவிதமான இழப்பு மற்றும்/அல்லது சேதத்தையும், எந்த தன்மையிலும், நாங்கள் பொறுப்பல்ல.',
    volunteerTermsConsent: 'தன்னார்வலருடன் தொடர்புடைய பதிவு செய்யும்போது நீங்கள் எங்களுக்கு வழங்கிய உங்கள் தனிப்பட்ட தகவல்களின் சேகரிப்பு மற்றும் பயன்பாட்டிற்கு நீங்கள் உங்கள் சம்மதத்தை வழங்குகிறீர்கள். எதிர்காலத்தில் வரக்கூடிய மேலும் தன்னார்வலர் வாய்ப்புகளின் விவரங்களை அனுப்ப நாங்கள் உங்கள் தகவலைப் பயன்படுத்தலாம்.',
    volunteerTermsFinal: 'Diya Charitable Trust எந்தவிதமான சேதங்களுக்கும் வேண்டுமென்றே அல்லது தற்செயலாகவே எந்த வழக்கிலும் பொறுப்பல்ல, எனவே நீங்கள் முதிர்ச்சியுடன் செயல்படவும், செயல்களுக்கு உரிமையை எடுத்துக்கொள்ளவும் அறிவுறுத்தப்படுகிறீர்கள்.',
    acceptTerms: 'நான் விதிமுறைகள் & நிபந்தனைகளைப் படித்து ஒப்புக்கொள்கிறேன்',
    acceptTermsRequired: 'உங்கள் விண்ணப்பத்தை சமர்ப்பிக்க நீங்கள் விதிமுறைகள் மற்றும் நிபந்தனைகளை ஏற்க வேண்டும்.',
    // Footer
    contactUs: 'எங்களைத் தொடர்பு கொள்ளுங்கள்',
    generalInquiries: 'பொது விசாரணைகள்',
    emergency: 'அவசரகால',
    officeLocation: 'அலுவலக இடம்',
    officeHours: 'அலுவலக நேரங்கள்',
    mondayFriday: 'திங்கள் - வெள்ளி: 9:00 AM - 6:00 PM',
    saturday: 'சனிக்கிழமை: 10:00 AM - 4:00 PM',
    sunday: 'ஞாயிற்றுக்கிழமை: மூடப்பட்டது',
    quickLinks: 'விரைவு இணைப்புகள்',
    legal: 'சட்டம்',
    followUs: 'எங்களைப் பின்தொடரவும்',
    india: 'இந்தியா',
    // Community Feedback Testimonials
    testimonial1Quote: 'டியா சாரிட்டி எங்கள் குழந்தைகளுக்கு இலவச கல்வி வழங்குவதன் மூலம் எங்கள் சமூகத்தை மாற்றியுள்ளது. அவர்கள் உண்மையில் வாழ்க்கையை ஒளிரச் செய்கிறார்கள்!',
    testimonial1Author: 'விஜயா',
    testimonial2Quote: 'டியா சாரிட்டி ஏற்பாடு செய்த சுகாதார முகாம்கள் எங்கள் கிராமத்திற்கு ஒரு ஆசீர்வாதமாக இருந்துள்ளன. நாங்கள் என்றென்றும் நன்றியுள்ளவர்கள்.',
    testimonial2Author: 'கண்ணன்',
    testimonial3Quote: 'அவர்களின் பெண்கள் அதிகாரமளித்தல் திட்டங்கள் மூலம், நான் என் சொந்த வணிகத்தைத் தொடங்க உதவிய திறன்களைக் கற்றுக்கொண்டேன். நன்றி டியா சாரிட்டி!',
    testimonial3Author: 'கவியா',
  },
  hi: {
    // Header
    donate: 'दान करें',
    // Hero
    heroWelcome: 'Diya Charitable Trust (TN) में आपका स्वागत है',
    heroMotto: '-मानवता सर्वोपरि-',
    heroTitle: 'सेवा के माध्यम से जीवन को रोशन करना',
    heroSubtitle: 'समुदायों को सशक्त बनाना, आशा का निर्माण करना',
    heroCta: 'हमारे मिशन में शामिल हों',
    // Mission
    missionTitle: 'हमारा मिशन',
    missionDescription: 'दीया चैरिटी में, हम एक नव स्थापित NGO हैं जो व्यापक सामाजिक कल्याण कार्यक्रमों के माध्यम से समाज की सेवा के लिए समर्पित हैं। हमारा मिशन शिक्षा, स्वास्थ्य सेवा, महिला सशक्तिकरण और पर्यावरणीय स्थिरता के माध्यम से वंचित समुदायों के जीवन को रोशन करना और आशा लाना है। एक दीया (दीपक) की तरह जो अंधकार को दूर करता है, हम सभी के लिए एक बेहतर कल का मार्ग प्रशस्त करने का प्रयास करते हैं।',
    // Contact
    contactTitle: 'संपर्क करें',
    contactDescription: 'समाज की सेवा करने के हमारे मिशन में हमसे जुड़ें। चाहे आप स्वयंसेवक बनना चाहते हों, दान करना चाहते हों, या हमारे साथ साझेदारी करना चाहते हों, हम आपसे सुनना पसंद करेंगे। एक साथ, हम उन लोगों के जीवन में एक अंतर ला सकते हैं जिन्हें इसकी सबसे अधिक आवश्यकता है।',
    // Footer
    footerCopyright: '© 2035 दीया चैरिटी द्वारा।',
    footerPoweredBy: 'Wix द्वारा संचालित और सुरक्षित',
    privacyPolicy: 'गोपनीयता नीति',
    accessibilityStatement: 'पहुंच योग्यता विवरण',
    accessibilityStatementDesc: 'Diya Charitable Trust विकलांग लोगों के लिए डिजिटल पहुंच सुनिश्चित करने के लिए प्रतिबद्ध है। हम सभी के लिए उपयोगकर्ता अनुभव में लगातार सुधार कर रहे हैं और प्रासंगिक पहुंच मानकों को लागू कर रहे हैं। हम वेब सामग्री पहुंच दिशानिर्देश (WCAG) 2.1 स्तर AA मानकों के अनुरूप होने का लक्ष्य रखते हैं। यदि आप हमारी वेबसाइट पर कोई पहुंच बाधा का सामना करते हैं, तो कृपया dctnow.ngo@gmail.com पर हमसे संपर्क करें और हम मुद्दे को हल करने के लिए काम करेंगे।',
    cancellationRefundsPolicy: 'रद्दीकरण और धनवापसी नीति',
    legalDisclaimerCompliance: 'कानूनी अस्वीकरण और अनुपालन',
    close: 'बंद करें',
    // Privacy Policy
    privacyIntro: 'Diya Charitable Trust इस वेबसाइट के आगंतुकों, दानदाताओं, स्वयंसेवकों और लाभार्थियों की गोपनीयता और व्यक्तिगत जानकारी की सुरक्षा के लिए प्रतिबद्ध है।',
    privacyInfoWeCollect: 'जानकारी जो हम एकत्र करते हैं',
    privacyInfoWeCollectDesc: 'जब आप निम्नलिखित करते हैं तो हम नाम, ईमेल पता, फोन नंबर, डाक पता, PAN विवरण (दान रसीदों के लिए), और भुगतान-संबंधी जानकारी जैसी व्यक्तिगत जानकारी एकत्र कर सकते हैं:\n\n• दान करना\n• स्वयंसेवक के रूप में पंजीकरण करना\n• फॉर्म या ईमेल के माध्यम से हमसे संपर्क करना\n• अपडेट या न्यूज़लेटर की सदस्यता लेना\n\nभुगतान जानकारी सुरक्षित तृतीय-पक्ष भुगतान गेटवे के माध्यम से संसाधित की जाती है, और हम अपने सर्वर पर कार्ड या बैंकिंग विवरण संग्रहीत नहीं करते हैं।',
    privacyUseOfInfo: 'जानकारी का उपयोग',
    privacyUseOfInfoDesc: 'एकत्र की गई जानकारी केवल निम्नलिखित उद्देश्यों के लिए उपयोग की जाती है:\n\n• दानों को संसाधित करना और रसीदें जारी करना\n• कार्यक्रमों, स्वीकृतियों और अपडेट के बारे में संवाद करना\n• भारतीय कानून द्वारा आवश्यक वैधानिक रिकॉर्ड बनाए रखना\n• हमारी सेवाओं और आउटरीच गतिविधियों में सुधार करना\n\nहम किसी भी तृतीय पक्ष को व्यक्तिगत जानकारी बेचते, किराए पर देते या व्यापार नहीं करते हैं।',
    privacyDisclosure: 'जानकारी का खुलासा',
    privacyDisclosureDesc: 'व्यक्तिगत जानकारी केवल निम्नलिखित स्थितियों में साझा की जा सकती है:\n\n• अधिकृत सेवा प्रदाताओं के साथ (भुगतान गेटवे, ऑडिटर, IT सेवाएं)\n• कानून या सरकारी अधिकारियों द्वारा आवश्यक होने पर\n\nऐसे सभी खुलासे सख्ती से आवश्यकता-से-जानने के आधार पर किए जाते हैं।',
    privacyDataSecurity: 'डेटा सुरक्षा',
    privacyDataSecurityDesc: 'अनधिकृत पहुंच, दुरुपयोग या खुलासे के खिलाफ व्यक्तिगत डेटा की सुरक्षा के लिए हम उचित प्रशासनिक और तकनीकी उपाय करते हैं।',
    privacyCookies: 'कुकीज़',
    privacyCookiesDesc: 'यह वेबसाइट उपयोगकर्ता अनुभव को बेहतर बनाने और वेबसाइट ट्रैफ़िक का विश्लेषण करने के लिए कुकीज़ का उपयोग कर सकती है। उपयोगकर्ता अपनी ब्राउज़र सेटिंग्स के माध्यम से कुकीज़ को अक्षम करना चुन सकते हैं।',
    privacyThirdPartyLinks: 'तृतीय-पक्ष लिंक',
    privacyThirdPartyLinksDesc: 'हमारी वेबसाइट में बाहरी वेबसाइटों के लिंक हो सकते हैं। हम ऐसी तृतीय-पक्ष साइटों की गोपनीयता प्रथाओं या सामग्री के लिए जिम्मेदार नहीं हैं।',
    privacyConsent: 'सहमति',
    privacyConsentDesc: 'इस वेबसाइट का उपयोग करके या व्यक्तिगत जानकारी जमा करके, आप इस गोपनीयता नीति के अनुसार जानकारी के संग्रह और उपयोग के लिए सहमति देते हैं।',
    privacyUpdates: 'इस नीति के अपडेट',
    privacyUpdatesDesc: 'इस गोपनीयता नीति को समय-समय पर अपडेट किया जा सकता है। किसी भी परिवर्तन को इस पृष्ठ पर पोस्ट किया जाएगा।',
    privacyContact: 'संपर्क जानकारी',
    privacyContactDesc: 'गोपनीयता-संबंधी किसी भी चिंता या अनुरोध के लिए, कृपया हमसे संपर्क करें:\nईमेल: dctnow.ngo@gmail.com',
    // Cancellation & Refunds Policy
    cancellationPolicyDesc1: 'Diya Charitable Trust को किए गए सभी दान, योगदान, प्रायोजन और भुगतान स्वैच्छिक और गैर-वापसी योग्य हैं।',
    cancellationPolicyDesc2: 'एक बार दान संसाधित हो जाने के बाद, इसे रद्द, उलट या वापस नहीं किया जा सकता है, क्योंकि धन तुरंत हमारे धर्मार्थ कार्यक्रमों और कल्याण गतिविधियों के लिए आवंटित किए जाते हैं।',
    cancellationPolicyDesc3: 'डुप्लिकेट लेनदेन, तकनीकी त्रुटियों, या गलत राशि डेबिट होने की स्थिति में, दानदाता लेनदेन के 7 दिनों के भीतर वैध प्रमाण के साथ हमें लिख सकते हैं। वास्तविक मामलों की समीक्षा की जाएगी, और यदि अनुमोदित हो तो धनवापसी उचित समय के भीतर संसाधित की जाएगी।',
    cancellationPolicyDesc4: 'Trust उपरोक्त शर्तों को पूरा न करने वाली किसी भी धनवापसी अनुरोध को अस्वीकार करने का अधिकार सुरक्षित रखता है।',
    cancellationPolicyDesc5: 'इस वेबसाइट पर दान करके, दानदाता इस नीति से सहमत होता है।\n\nकिसी भी चिंता के लिए, कृपया संपर्क करें: dctnow.ngo@gmail.com',
    // Legal Disclaimer & Compliance
    legalDisclaimerDesc1: 'Diya Charitable Trust भारतीय Trusts Act, 1882 के तहत पंजीकृत एक धर्मार्थ ट्रस्ट है। Trust गैर-लाभकारी आधार पर काम करता है और शिक्षा, पोषण, स्वास्थ्य सेवा और सामुदायिक विकास सहित सामाजिक कल्याण गतिविधियों के लिए प्रतिबद्ध है।',
    legalDisclaimerDesc2: 'प्राप्त सभी दान केवल Trust के उद्देश्यों के लिए उपयोग किए जाते हैं। Trust की आय या संपत्ति का कोई भी हिस्सा ट्रस्टी, सदस्यों या किसी भी निजी व्यक्ति को वितरित नहीं किया जाता है, सिवाय इसके कि इसके धर्मार्थ उद्देश्यों को आगे बढ़ाने में प्रदान की गई सेवाओं के लिए उचित मुआवजे के रूप में।',
    legalDisclaimerDesc3: 'दान स्वैच्छिक और गैर-वापसी योग्य हैं। दान रसीदों और कर लाभों का जारी करना, यदि लागू हो, तो प्रचलित कानूनों के अधीन होगा।\nIncome Tax Act, 1961 की धारा 80G के तहत कर छूट उपलब्ध है। दानदाताओं को अपनी पात्रता की पुष्टि के लिए अपने कर सलाहकारों से परामर्श करने की सलाह दी जाती है।',
    legalDisclaimerDesc4: 'इस समय FCRA पंजीकरण प्रक्रिया पूर्ण होने तक, Trust विदेशी योगदान स्वीकार नहीं करता है, जब तक कि Foreign Contribution (Regulation) Act, 2010 के तहत स्पष्ट रूप से अनुमति न दी गई हो।',
    legalDisclaimerDesc5: 'इस वेबसाइट पर प्रकाशित सभी सामग्री—पाठ, छवियां, लोगो और सामग्री सहित—जब तक अन्यथा न कहा गया हो, Diya Charitable Trust की बौद्धिक संपदा है। अनधिकृत उपयोग, प्रजनन या वितरण निषिद्ध है।',
    legalDisclaimerDesc6: 'हालांकि सटीकता सुनिश्चित करने के लिए हर प्रयास किया जाता है, Trust इस वेबसाइट पर जानकारी के उपयोग से उत्पन्न होने वाली किसी भी त्रुटि, चूक या परिणामों के लिए उत्तरदायी नहीं होगा।',
    legalDisclaimerDesc7: 'इस वेबसाइट तक पहुंचकर या उपयोग करके, आप इन नियमों और शर्तों से बाध्य होने के लिए सहमत होते हैं।',
    // Mission additional
    missionQuestion1: 'क्या आपने कभी अत्यधिक गरीबी से उत्पन्न भूख की पीड़ा महसूस की है - यहां तक कि दुर्भाग्य के कारण अचानक शहरी गरीबी इतनी गहरी कि आप अपने संघर्षों को परिवार की गरिमा के कारण किसी के साथ साझा नहीं कर सके? क्या आपने नौकरी खोने के तनाव का सामना किया है, साथ ही वह भावनात्मक उथल-पुथल जो यह आपके और आपके परिवार के लिए लाता है? क्या आपने सफलता की दौड़ में पीछे रह जाने या उम्र के साथ आने वाली चुनौतियों से अकेलापन या अवसाद का अनुभव किया है? या किसी को, किसी चीज को याद करने का दर्द, या अपने प्रियजनों की जरूरतों को पूरा करने में असमर्थ होने की असहायता?',
    missionComfort: 'हम यहां एक सांत्वना देने वाली उपस्थिति हैं - आपका समर्थन करने, आपको उठाने और आगे बढ़ने में मदद करने के लिए एक उपचार करने वाला हाथ।',
    missionInvitation: 'यदि आप, पाठक, ईश्वर द्वारा आशीर्वादित महसूस करते हैं, आराम से रहते हैं, और सुरक्षित महसूस करते हैं, तो हम आपको स्वयंसेवक के रूप में हमसे जुड़ने के लिए अपना समय देने के लिए आमंत्रित करते हैं (या) अपनी प्रचुरता का एक छोटा सा हिस्सा भी दान करके योगदान करते हैं। याद रखें, जो चारों ओर जाता है वह गुणकों में वापस आता है!',
    missionAnonymous: 'हमारा हर आउटरीच गुमनाम होगा। पेशेवर स्वयंसेवकों को छोड़कर बाहर किसी को पता नहीं चलेगा! 1234567890 पर whatsapp के माध्यम से हमसे संपर्क करें, आपको तत्काल उत्तर नहीं मिल सकते हैं लेकिन निश्चित रूप से हम आपसे संपर्क करेंगे!',
    missionActions: 'हम कौन हैं इससे कोई फर्क नहीं पड़ता! हमारे कार्य बोलें !!',
    volunteer: 'स्वयंसेवक',
    ourCompliance: 'हमारी अनुपालन',
    // Donation
    needSupport: 'समर्थन की आवश्यकता - दान करें',
    taxBenefit: 'कर लाभ प्राप्त करें (80G के तहत)',
    taxBenefitDesc: 'दान धारा 80G छूट के लिए पात्र हैं। दान करने के बाद हमारे',
    taxBenefitDescAfter: 'पर अपना PAN साझा करें।',
    whatsapp: 'WhatsApp',
    lifeIsEcho: 'जीवन एक प्रतिध्वनि है',
    echo1: 'जो आप भेजते हैं वह वापस आता है। जो आप बोते हैं वही आप काटते हैं।',
    echo2: 'जो आप देते हैं वही आपको मिलता है। दूसरों में जो आप देखते हैं वह आप में मौजूद है।',
    donorInfo: 'दाता जानकारी और योगदान',
    donorName: 'दाता का नाम *',
    phoneNumber: 'फोन नंबर *',
    emailAddress: 'ईमेल पता *',
    selectAmount: 'दान राशि चुनें (INR)',
    otherAmount: 'अन्य राशि',
    enterCustomAmount: 'कस्टम राशि दर्ज करें',
    donationType: 'दान प्रकार',
    oneTimeDonation: 'एक बार का दान',
    monthlyDonation: 'मासिक दान',
    monthlyDonationNote: 'पंजीकरण की तारीख से हर महीने आपका दान स्वचालित रूप से काटा जाएगा।',
    proceedPayment: 'भुगतान के लिए आगे बढ़ें',
    directPayment: 'प्रत्यक्ष भुगतान विवरण',
    scanPay: 'स्कैन और भुगतान (UPI)',
    upiQr: 'UPI QR',
    upiPlaceholder: '[ट्रस्ट के UPI QR कोड छवि के लिए प्लेसहोल्डर]',
    upiId: 'UPI ID',
    copy: 'कॉपी करें',
    copied: 'कॉपी हो गया!',
    bankTransfer: 'बैंक ट्रांसफर विवरण',
    accountName: 'खाता नाम',
    bankName: 'बैंक का नाम',
    accountNumber: 'खाता संख्या',
    ifscCode: 'IFSC कोड',
    transactionNote: '*80G रसीद के लिए ईमेल/WhatsApp के माध्यम से लेनदेन विवरण साझा करें।*',
    corporateSponsors: 'हमारे कॉर्पोरेट और सरकारी प्रायोजक',
    underCSR: 'CSR पहल के तहत',
    corporatePartner: 'कॉर्पोरेट भागीदार',
    anticipatingCSR: 'आपके CSR प्रायोजन की प्रतीक्षा कर रहे हैं।',
    metricsImpact: 'मेट्रिक्स और प्रभाव क्षेत्र',
    educationYouth: 'शिक्षा और युवा',
    elderlyCare: 'वृद्ध देखभाल',
    womenFamilies: 'महिलाएं और परिवार',
    emergencyRelief: 'आपातकालीन राहत',
    willBeShared: '---------- कार्यक्रम प्रायोजकों के साथ साझा किया जाएगा -------------',
    // Property Donation
    propertyDonationPara1: 'एक धर्मार्थ संगठन के रूप में, हमारा काम केवल दान और प्रायोजन के माध्यम से निरंतर है। शिक्षा और भोजन केंद्रों के समूह स्थापित करने के लिए, उपयुक्त स्थान तक पहुंच आवश्यक है।',
    propertyDonationPara2: 'यदि आप परोपकारी रूप से प्रवृत्त हैं और आपकी परिस्थितियां अनुमति देती हैं, तो हम आपको ट्रस्ट को भूमि या संपत्ति दान करने और एक स्थायी विरासत बनाने के लिए आमंत्रित करते हैं। संपत्ति विशेष रूप से सामान्य भलाई के लिए समर्पित होगी, और आपका योगदान पीढ़ियों तक सम्मानित किया जाएगा।',
    propertyDonationNote: 'कृपया ध्यान दें कि संपत्ति गैर-पैतृक होनी चाहिए और बाधाओं से मुक्त होनी चाहिए।',
    propertyDonationContact: 'कृपया कानूनी प्रक्रिया शुरू करने के लिए हमें संदेश भेजें।',
    // Community Feedback
    communityFeedback: 'समुदाय प्रतिक्रिया',
    // Process
    ourProcess: 'हमारी प्रक्रिया',
    joinUs: 'हमसे जुड़ें',
    // Impact Stats
    ourImpact: 'हमारा प्रभाव',
    impactDescription: 'हमारी स्थापना के बाद से, हम अनगिनत व्यक्तियों और समुदायों के जीवन में सार्थक अंतर ला रहे हैं।',
    childrenEducated: 'बच्चे शिक्षित',
    childrenEducatedDesc: 'वंचित बच्चों को गुणवत्तापूर्ण शिक्षा प्रदान करना',
    healthcareCamps: 'स्वास्थ्य शिविर',
    healthcareCampsDesc: 'ग्रामीण क्षेत्रों में चिकित्सा शिविर आयोजित करना',
    womenEmpowered: 'महिलाएं सशक्त',
    womenEmpoweredDesc: 'महिलाओं को व्यावसायिक कौशल में प्रशिक्षण',
    villagesReached: 'गांव पहुंचे',
    villagesReachedDesc: 'दूरस्थ समुदायों तक अपनी सेवाओं का विस्तार',
    joinMakingDifference: 'अंतर लाने में हमसे जुड़ें',
    joinMakingDifferenceDesc: 'हर योगदान, चाहे वह कितना भी छोटा क्यों न हो, हमें अधिक लोगों तक पहुंचने और समुदायों में स्थायी परिवर्तन लाने में मदद करता है।',
    donateNow: 'अभी दान करें',
    // Annathanam
    annathanam: 'अन्नदान',
    annathanamQuote: 'अन्नदान दान नहीं है - यह सेवा है।',
    annathanamDesc1: 'आप किसी को खाना नहीं देते; आप उनके माध्यम से भगवान को खाना परोसते हैं।',
    annathanamDesc2: 'कई परंपराओं में, कहा जाता है:',
    annathanamQuote2: 'जो खाता है वह भगवान है जो छुपा हुआ है।',
    annathanamDesc3: 'अन्नदान को महसूस करने के लिए आपको अत्यधिक गरीबी के कारण अत्यधिक भूख का अनुभव करने की आवश्यकता है! अत्यधिक गरीबी के अलावा, कई लोग गर्व और आत्म-सम्मान के कारण मदद मांगने से हिचकिचाते हैं - जैसे विस्थापित छात्र, दैनिक मजदूरों के बच्चे, मजदूर खुद, अनाथ खानाबदोश, या वे भी जो छोटी आय कमाते हैं लेकिन फिर भी गुजारा करने के लिए संघर्ष करते हैं।',
    annathanamDesc4: 'यदि हमारा अन्नदान उनके बोझ को कम कर सकता है और उन्हें आर्थिक सीढ़ी पर चढ़ने में मदद कर सकता है, तो क्यों नहीं? हम जाति, पंथ, लिंग या धर्म से परे किसी भी व्यक्ति को बिना गर्व के खाना परोसते हैं!',
    // Primary Activities
    primaryActivitiesTitle: 'हमारी प्राथमिक गतिविधियाँ और प्रभाव क्षेत्र',
    buddingMinds: 'उभरते दिमाग',
    buddingMindsDesc: 'स्कूल ड्रॉपआउट अंतराल को पाटना, कौशल प्रशिक्षण, और वंचित युवाओं के लिए नौकरी प्लेसमेंट सहायता।',
    youthLeap: 'युवा छलांग',
    youthLeapDesc: 'युवा सशक्तिकरण के लिए विशेष रूप से डिज़ाइन किया गया कौशल प्रशिक्षण, मनोवैज्ञानिक परामर्श, और प्लेसमेंट सहायता।',
    vulnerableWomenFamilies: 'कमजोर महिलाएं और परिवार',
    vulnerableWomenFamiliesDesc: 'महिलाओं के लिए आर्थिक स्थिरता पर केंद्रित कौशल प्रशिक्षण, नौकरी प्लेसमेंट, और स्वयं सहायता समूह गठन।',
    oldAgeCare: 'वृद्ध देखभाल',
    oldAgeCareDesc: 'बुजुर्ग समुदाय के लिए पैलिएटिव केयर, परामर्श, और सुलभ स्वास्थ्य सेवाएं।',
    supportSustainability: 'पर्यावरण और स्थिरता',
    supportSustainabilityDesc: 'दीर्घकालिक सामुदायिक लचीलापन के लिए जागरूकता अभियान और स्थिरता प्रयास।',
    explore: 'अन्वेषण करें',
    // Volunteer Form
    volunteerSignUp: 'स्वयंसेवक पंजीकरण फॉर्म',
    personalInformation: 'व्यक्तिगत जानकारी',
    firstName: 'पहला नाम *',
    gender: 'लिंग',
    selectGender: 'लिंग चुनें',
    male: 'पुरुष',
    female: 'महिला',
    nonBinary: 'नॉन-बाइनरी',
    preferNotToSay: 'कहना पसंद नहीं',
    enterFirstName: 'अपना पहला नाम दर्ज करें',
    volunteerPreferences: 'स्वयंसेवक वरीयताएं',
    eventSetup: 'इवेंट सेटअप',
    registrationDesk: 'पंजीकरण डेस्क',
    hospitalityGuestServices: 'आतिथ्य/अतिथि सेवाएं',
    workshopFacilitation: 'कार्यशाला सुविधा',
    marketingPromotion: 'मार्केटिंग/प्रचार',
    fundraising: 'फंडरेजिंग',
    generalSupport: 'सामान्य सहायता',
    teaching: 'शिक्षण',
    availability: 'उपलब्धता',
    morning: 'सुबह (8am-12pm)',
    afternoon: 'दोपहर (12pm-5pm)',
    evening: 'शाम (5pm-9pm)',
    weekdays: 'सप्ताह के दिन',
    weekends: 'सप्ताहांत',
    flexibleSchedule: 'लचीला कार्यक्रम',
    additionalComments: 'अतिरिक्त टिप्पणियां',
    tellUsWhy: 'हमें बताएं कि आप स्वयंसेवक क्यों बनना चाहते हैं',
    enterAdditionalNotes: 'कोई अतिरिक्त नोट्स, कौशल, या विशिष्ट समय बाधाएं दर्ज करें...',
    submitVolunteerApplication: 'स्वयंसेवक आवेदन जमा करें',
    sending: 'भेज रहे हैं...',
    volunteerTerms: 'जमा करके, आप हमारी स्वयंसेवक शर्तों और नियमों से सहमत हैं।',
    volunteerTermsTitle: 'अपने आप को गिनने का समय',
    volunteerTermsSubtitle: '"एकता शक्ति है" जब सहयोग और टीम वर्क होता है, तो अद्भुत चीजें हो सकती हैं। वहां अपना समय स्वेच्छा से दें जहां सबसे अधिक फर्क पड़ता है:',
    volunteerTermsContent: 'हमारी टीम आपकी अद्वितीय कौशल सेट, क्षमताओं, जुनून, प्रतिभा और रुचियों की पहचान करेगी और आपको एक उपयुक्त परियोजना से मिलाएगी जहां आप सबसे अधिक फर्क कर सकते हैं।',
    volunteerTermsOpportunities: 'व्यापक अवसर:',
    volunteerTermsOpportunitiesDesc: 'हमारे पास आभासी और व्यक्तिगत रूप से, परामर्श, शिक्षण, व्यावसायिक प्रशिक्षण, रचनात्मक कला, खेल प्रशिक्षण, करियर मार्गदर्शन, जागरूकता अभियान, सामुदायिक विकास, गांव उत्थान, समुद्र तट सफाई, झील बहाली, पशु कल्याण, रचनात्मक सामग्री विकास सहित व्यापक अवसर हैं जहां आपके कौशल सेट, कनेक्शन और व्यक्तित्व आपके समुदाय में स्थायी प्रभाव डाल सकते हैं।',
    volunteerTermsMedia: 'स्वेच्छा से काम करते समय, हम अपने उपयोग के लिए तस्वीरें, वीडियो और लिखित प्रतिक्रिया/अनुभव ले सकते हैं।',
    volunteerTermsBelongings: 'कृपया सुनिश्चित करें कि आप अपने स्वयंसेवक कार्य के दौरान पैसे, सामान और व्यक्तिगत चीजों जैसी अपनी सभी संपत्तियों की देखभाल करते हैं।',
    volunteerTermsLiability: 'आपके स्वयंसेवक अवधि के दौरान आपके पैसे, सामान और व्यक्तिगत चीजों की किसी भी तरह की हानि/चोरी के लिए हम जिम्मेदार नहीं होंगे।',
    volunteerTermsConfidential: 'आपकी गतिविधि में हमारे बारे में, आपको सौंपे गए विषयों और कार्यों के बारे में कुछ जानकारी जानना शामिल हो सकता है। इस तरह की जानकारी को "गोपनीय जानकारी" के रूप में माना जाएगा और आप कानून द्वारा आवश्यक होने तक हमारी पूर्व अनुमति के बिना किसी के साथ ऐसी जानकारी साझा नहीं करने के लिए सहमत हैं।',
    volunteerTermsConduct: 'एक स्वयंसेवक के रूप में, अपने लिए और हमारे आसपास के दूसरों के लिए एक सुरक्षित, सहायक, सीखने का माहौल बनाने के लिए इस तरह से होना महत्वपूर्ण है। इसलिए, हम आपसे अनुरोध करते हैं कि आप किसी भी विघटनकारी भाषण या व्यवहार में शामिल न हों।',
    volunteerTermsSubstances: 'धूम्रपान, शराब पीना या किसी भी मतिभ्रम या प्रतिबंधित दवा का सेवन करना सख्त वर्जित है।',
    volunteerTermsStandards: 'आप सभी स्वयंसेवक गतिविधियों को उच्च मानकों और अच्छे स्वाद के साथ आचरण करने के लिए सहमत हैं, और हमारी प्रतिष्ठा या सद्भावना को नुकसान पहुंचाने के लिए कुछ भी नहीं करेंगे।',
    volunteerTermsDocumentation: 'आप स्वयंसेवक के रूप में अपने पंजीकरण के उद्देश्य के लिए आवश्यक सभी विवरण और दस्तावेज प्रदान करने के लिए सहमत हैं।',
    volunteerTermsForceMajeure: '"फोर्स माजेयर इवेंट" की स्थिति में, जिसमें सरकारी प्रतिबंध, दंगे, आतंकवादी हमले, महामारी, संगरोध, महामारी, भूकंप, तूफान, बाढ़, बिजली जैसी प्राकृतिक आपदाएं, या ईश्वर के कार्य शामिल हैं, हमारे पास कार्यक्रम को रद्द करने का अधिकार सुरक्षित है।',
    volunteerTermsCancellation: 'यदि आपका स्वयंसेवक कार्य रद्द कर दिया जाता है, तो आपको सूचित किया जाएगा, और आपको उस जानकारी के आधार पर अपनी यात्रा योजनाओं को समायोजित करना होगा।',
    volunteerTermsCancellationLiability: 'आपके स्वयंसेवक कार्य के रद्द होने के परिणामस्वरूप आपको जो भी हानि और/या क्षति हो सकती है, उसके लिए हम जिम्मेदार नहीं होंगे।',
    volunteerTermsConsent: 'आप स्वयंसेवक से संबंधित पंजीकरण करते समय हमें प्रदान की गई आपकी व्यक्तिगत जानकारी के संग्रह और उपयोग के लिए हमें अपनी सहमति देते हैं। हम आपकी जानकारी का उपयोग भविष्य में आने वाले किसी भी आगे के स्वयंसेवक अवसरों के विवरण भेजने के लिए कर सकते हैं।',
    volunteerTermsFinal: 'Diya Charitable Trust किसी भी क्षति के लिए जानबूझकर या अनजाने में जो भी मामला हो, जिम्मेदार नहीं होगा और इसलिए आपको परिपक्वता के साथ कार्य करने और कार्यों के लिए स्वामित्व लेने की सलाह दी जाती है।',
    acceptTerms: 'मैंने नियम और शर्तें पढ़ ली हैं और उनसे सहमत हूं',
    acceptTermsRequired: 'अपना आवेदन जमा करने के लिए आपको नियम और शर्तें स्वीकार करनी होंगी।',
    // Footer
    contactUs: 'संपर्क करें',
    generalInquiries: 'सामान्य पूछताछ',
    emergency: 'आपातकाल',
    officeLocation: 'कार्यालय स्थान',
    officeHours: 'कार्यालय समय',
    mondayFriday: 'सोमवार - शुक्रवार: 9:00 AM - 6:00 PM',
    saturday: 'शनिवार: 10:00 AM - 4:00 PM',
    sunday: 'रविवार: बंद',
    quickLinks: 'त्वरित लिंक',
    legal: 'कानूनी',
    followUs: 'हमें फॉलो करें',
    india: 'भारत',
    // Community Feedback Testimonials
    testimonial1Quote: 'डिया चैरिटी ने हमारे बच्चों को मुफ्त शिक्षा प्रदान करके हमारे समुदाय को बदल दिया है। वे वास्तव में जीवन को रोशन करते हैं!',
    testimonial1Author: 'विजया',
    testimonial2Quote: 'डिया चैरिटी द्वारा आयोजित स्वास्थ्य शिविर हमारे गांव के लिए एक वरदान रहे हैं। हम हमेशा आभारी हैं।',
    testimonial2Author: 'कन्नन',
    testimonial3Quote: 'उनके महिला सशक्तिकरण कार्यक्रमों के माध्यम से, मैंने ऐसे कौशल सीखे जिन्होंने मुझे अपना व्यवसाय शुरू करने में मदद की। धन्यवाद डिया चैरिटी!',
    testimonial3Author: 'कविया',
  },
};

const languageNames: Record<Language, string> = {
  en: 'English',
  ta: 'Tamil',
  hi: 'Hindi',
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check localStorage first
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ta' || savedLanguage === 'hi')) {
      return savedLanguage;
    }
    // Default to English
    return 'en';
  });

  useEffect(() => {
    // Save language preference
    localStorage.setItem('language', language);
    // Update document language attribute
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const getLanguageName = (code: Language): string => {
  return languageNames[code];
};

